metadata:
  id: example-sparv-sbx-sentence-kb-sent-issue-10
  language: swe

# import:
#     importer: text_import:parse

sbx_sentiment_kb_sent:
  num_decimals: 3

export:
  annotations:
    - <sentence>
    # - <token:word>
    - <token>:stanza.pos
    - <sentence>:sbx_sentiment_kb_sent.sentiment--kb-sent

sparv:
  compression: none
